name: Reusable workflow deployment
 
on:
  workflow_call:
    inputs:
      CONJUR_VARIABLE_PATH:
        description: "Conjur variable path for organizational secrets"
        required: true
        type: string
    secrets:
      CONJUR_URL:
        required: true
      CONJUR_ACCOUNT:
        required: true
      CONJUR_HOST_ID:
        required: true
      CONJUR_API_KEY:
        required: true

    outputs:
      WIZ_CLIENT_SECRET:
        value: ${{ jobs.conjur.outputs.WIZ_CLIENT_SECRET }}

 
jobs:
  conjur:
    runs-on: ubuntu-latest
    outputs:
      WIZ_CLIENT_SECRET: ${{ steps.set-output.outputs.WIZ_CLIENT_SECRET }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
 
      - name: Fetch secrets from Conjur
        id: fetch
        uses: cyberark/conjur-action@v2.0.12
        with:
          url: ${{ secrets.CONJUR_URL }}
          account: ${{ secrets.CONJUR_ACCOUNT }}
          host_id: ${{ secrets.CONJUR_HOST_ID }}
          api_key: ${{ secrets.CONJUR_API_KEY }}
          secrets: ${{ inputs.CONJUR_VARIABLE_PATH }}|wiz_client_secret

      - name: Set Outputs
        id: set-output
        run: |
          echo "WIZ_CLIENT_SECRET=$WIZ_CLIENT_SECRET" >> $GITHUB_OUTPUT
